name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1f6ab28671aa55c4039f1b57765806ea0ed89c4c5da620c5ab58da0b01d6964"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
