name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e12adf0aa131164fe065bd27919ef00d9bbee391b9494f3c9de0a03ed165b637"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
