name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd10929b490d0d471196ada7ffc7904f2facce902c389bd4e300692789a2208d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
