name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d47e1d8619aff4133ecc749401d0085c6944e9ea16cfe862e7817039f987861"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
