name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b36cec4140c50a831a22454f8962e0a38585609febbc6463c41261c2632988"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
