name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "720ab6c911bc82761f466291e6c857daf61c9cbc202ba1a8bb0d5020804eea33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
