name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af6c6732b2a0dbffbfcbc88631134ace8523863d3a61c13f46450ac73b8c8e91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
