name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4105f174a92ca73b29c0f1412cddc0beb0e6761d164eb24e2f1064a0b69bbb1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
