name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a77d16c8de5f7b37d8db9bec6b1a15e0e597966c17efa3f2ba39979e0dd946"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
