name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "908a4dc2d5d5a780c2621ff7fd29b6d2cbf415483dcb2936c35eb62ad804b96c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"
