name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2188766f50784095655b807b9e99021189193b84f66de66a11fab328036a1d4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
