name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7318a76ca5791fee8519c783aa3053da6a2913c5e622e64f7a0e7cc436946a46"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
