name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef308e5c659e5cb7e9fb0b70d6f221e40b1b12b263df1fd6003bc1b933b6b8ec"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
