name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db79874dac406dc6efa2dfe0926df9d9d2ba9aea19f52ee08d34b464cd15edc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
