name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d904b8bff4528426fa674fba1d3da4066bba52c0eb8be8e3fd360337f594b0c8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
