name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ae36c66453acb3706216f54040fe8a6b1775c84c5dd9a48c93ebcfd34b69f2f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
