name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50cae4c1195fd2649f42fac0ef519e3e1dad48fc13785c4e319c9568391cf59b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
