name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55a4be74e21651f0de54996fddd13b3a4e423a2e69ba5185b4f63c03fcac1e37"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
