name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "061e26b54a105eac9a5b012ccd7918933910869758e6e4da51945a2fcb4e779b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
