name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "992ed55bfa0b0405ddc1418a62e0c6e684abaf47b417230bfe21562008a4343f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
