name = "modded smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42ed65ec8acc2a16881e565d336fa354443a30e2a686c578d5d11aa1f716d3c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
